# Generated by Django 5.1.6 on 2025-02-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pickup', 'Pickup'), ('En Route', 'En Route'), ('Dropoff', 'Dropoff')], default='Pickup', max_length=8, verbose_name='status')),
                ('pickup_latitude', models.FloatField(verbose_name='pickup latitude')),
                ('pickup_longitude', models.FloatField(verbose_name='pickup longitude')),
                ('dropoff_latitude', models.FloatField(verbose_name='dropoff latitude')),
                ('dropoff_longitude', models.FloatField(verbose_name='dropoff longitude')),
                ('pickup_time', models.DateTimeField(verbose_name='pickup time')),
            ],
            options={
                'verbose_name': 'rides',
                'verbose_name_plural': 'rides',
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'ride event',
                'verbose_name_plural': 'ride events',
            },
        ),
    ]
